# Generated by Django 5.1.4 on 2024-12-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='invert_transactions',
            field=models.BooleanField(default=False),
        ),
    ]
