# Generated by Django 5.1.4 on 2024-12-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_category_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='post_date',
            field=models.DateField(blank=True, null=True, verbose_name='Posting Date'),
        ),
    ]
